pub mod pb {
    // Generated by prost from trondb.proto. The variant-size lint fires on
    // generated oneofs, which we do not control; boxing them would change the
    // wire-compatible generated API for no benefit.
    #![allow(clippy::large_enum_variant)]

    tonic::include_proto!("trondb");
}

pub mod convert_health;
pub mod convert_plan;
pub mod convert_result;
pub mod convert_wal;
